version: '3.6'

services:
  web:
    build: .
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
      MOODLE_WWWROOT: ${MOODLE_WWWROOT}
  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./.docker/pg_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: /var/lib/postgresql/data
volumes:
  pgdata:
    driver: local
